# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=100)),
                ('release_date', models.CharField(default='', max_length=12)),
                ('video_release_date', models.CharField(max_length=12)),
                ('imdb_url', models.CharField(max_length=300)),
                ('genre_unknown', models.IntegerField()),
                ('genre_action', models.IntegerField()),
                ('genre_adventure', models.IntegerField()),
                ('genre_animation', models.IntegerField()),
                ('genre_children', models.IntegerField()),
                ('genre_comedy', models.IntegerField()),
                ('genre_crime', models.IntegerField()),
                ('genre_documentary', models.IntegerField()),
                ('genre_drama', models.IntegerField()),
                ('genre_fantasy', models.IntegerField()),
                ('genre_film_noir', models.IntegerField()),
                ('genre_horror', models.IntegerField()),
                ('genre_musical', models.IntegerField()),
                ('genre_mystery', models.IntegerField()),
                ('genre_romance', models.IntegerField()),
                ('genre_scifi', models.IntegerField()),
                ('genre_thriller', models.IntegerField()),
                ('genre_war', models.IntegerField()),
                ('genre_western', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ratings_app.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ratings_app.Rater')),
            ],
        ),
    ]
