# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='', max_length=12),
        ),
    ]
