# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 16:32
from __future__ import unicode_literals

from django.db import migrations

from movie_ratings_app.worker import add_movie_data
from movie_ratings_app.worker import add_rater_data

class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_movie_data),
        migrations.RunPython(add_rater_data)
    ]
