# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 03:07
from __future__ import unicode_literals

from django.db import migrations

from movie_ratings_app.worker import add_movie_data
from movie_ratings_app.worker import add_rater_data
from movie_ratings_app.worker import add_rating_data

class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings_app', '0002_auto_20160607_1858'),
    ]

    operations = [
        migrations.RunPython(add_movie_data),
        migrations.RunPython(add_rater_data),
        migrations.RunPython(add_rating_data)
    ]
